### ISSUE TITLE
January is being assumed as the future.

### ISSUE THREAD

**Issue by chadfawcett** [tickbin/filter-parser#11]
It appears that when parsing something like `Jan - Feb` it is assuming you mean `Feb 2016 - Jan 2017` but I actually wanted `Jan 2016 - Feb 2016`

![screen shot 2016-07-13 at 11 46 11 am](https://cloud.githubusercontent.com/assets/3250463/16815756/ee7d4858-48ef-11e6-93dc-c7fdf16248ce.png)

**Comment by chadfawcett** [comment]
This is now happening for February

**Comment by chrisfosterelli** [comment]
Closing this as this repository is no longer maintained
