### ISSUE TITLE
Move into tickbin/parser

### ISSUE THREAD

**Issue by chrisfosterelli** [tickbin/filter-parser#12]
@chadfawcett and I were discussing that with tickbin/parser containing both `Entry`, and a parser for entries, and eventually a parser for timers, it feels like an odd division to have filter-parser as a separate module.

We should consider joining the two together eventually. @tickbin/core can anyone think of any reasons why we should or should not do this?

**Comment by jonotron** [comment]
I'm slightly opposed to this as `filter-parser` has different concerns. While [tickbin/parser](https://github.com/tickbin/parser) parses things and eventually creates `Entry` objects, `filter-parser` parses strings and creates filters or query objects. There are things that this library ought to be able to do in the future that are of no concern of

**Comment by chrisfosterelli** [comment]
I see what you mean, it just feels odd to divide the responsibilities like so:

**parser** provides:
* `Entry` class
* commit string parser
* timer start string parser
* timer stop string parser

**filter-parser** provides:
* filter string parser

Perhaps merging isn't the correct solution here, but laid out as above seems relatively confusing to me. It leaves tickbin/parser feeling like a grab bag of things and tickbin/filter-parser oddly separate.

**Comment by jonotron** [comment]
maybe entry needs to be removed, or parser needs to be broken apart a bit more.

**Comment by chrisfosterelli** [comment]
Closing this as this repository is no longer maintained
